version: "3.8"

services :
  # Service frontend Reactjs
  frontend:
    build:
      context: ./frontend/reactjs-puissance4
      dockerfile: Dockerfile
    container_name: puissance4-react-container
    ports:
      - "3000:8080"
    depends_on:
      - backend
    environment:
      - REACT_APP_SERVER_URL=http://localhost:4000

  # Service backend Socket.IO
  backend:
    build:
      context: ./backend/puissance4-socket
      dockerfile: Dockerfile
    container_name: puissance4-server-container
    ports:
      - "4000:4000"
    environment:
      - CLIENT_URL=http://localhost:3000
networks:
  default:
    name: puissance4-network
